"""Leg 169 (Route-HHB) -- leg 119's battery, BANKED AS A PERMANENT REGRESSION SUITE.

The gate's YES branch says exactly this: "Repair confirmed solid and non-regressive.  Bank
leg 119's battery as a permanent regression suite."  This file is that bank.

It is NOT leg 153's own inverted test file (test_hilbert_holder_adversarial.py) -- that file
was written in the same commit as the repair it verifies, which is why leg 169 exists at all.
The load-bearing checks below are re-run LIVE against the working tree and against the
pre-repair blob `07f2b03` loaded out of git in the same process; the expensive censuses are
asserted from `writeup/data/p2_route_hhb_v1_postrepair.json`, regenerated by
`experiments/p2_route_hhb_v1_postrepair.py`.

What each check would catch:

  1  the guard removed, or weakened at either entry point          -> gates 1, 2
  2  the guard over-firing and rejecting a SOUND configuration     -> gate 3
  3  the guard becoming an epsilon-threshold instead of gamma > 0  -> gate 4
  4  the harness going blind, so every zero above is vacuous       -> gate 5  (LESSON 90)
  5  any previously-validated number moving by one bit             -> gate 6
  6  the capabilities-registered validated line breaking           -> gate 7
  7  'inflate' silently handing back a finite non-dominating pair  -> gate 8
  8  the rejections becoming heterogeneous (leg 147's NO shape)    -> gate 9
  9  leg 119's frozen runner silently starting/stopping to run     -> gate 10

Gate 5 is the load-bearing one and it is deliberately an INEQUALITY IN THE OTHER DIRECTION:
the pre-repair arm must still ACCEPT what the repaired arm rejects.  Per lesson 90, a control
that cannot come out differently is not a control -- if this suite ever reports that both arms
reject everything, it has stopped testing anything, and gate 5 is what fails first.

Every magnitude below was measured on 2026-08-06 and is quoted from the JSON.

Run: python test_hilbert_holder_postrepair.py     (~40 s)
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import subprocess
import sys
import types
import warnings

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from solver import hilbert_holder as HH                                      # noqa: E402

DATA = os.path.join(HERE, "writeup", "data", "p2_route_hhb_v1_postrepair.json")
PRE_REPAIR_PIN = "07f2b03"

# leg 119's failing set, exactly as leg 153 enumerated it in its own banked JSON
FAILING = {
    "V1_gamma_0.0":  (1.5, 0.0),
    "V2_gamma_-0.5": (1.5, -0.5),
    "gamma_-1.0":    (1.5, -1.0),
    "gamma_-0.3":    (1.5, -0.3),
    "gamma_nan":     (1.5, float("nan")),
    "gamma_inf":     (1.5, float("inf")),
    "alpha_nan":     (float("nan"), 0.5),
    "alpha_inf":     (float("inf"), 0.5),
}

SOUND = {
    "shipped_1.5_0.5":     (1.5, 0.5),
    "production_1.4_0.15": (1.4, 0.15),
    "gamma_0.9":           (1.5, 0.9),
    "gamma_0.05":          (1.5, 0.05),
    "gamma_0.01":          (1.5, 0.01),
    "gamma_1e-3":          (1.5, 1e-3),
}


def _ok(n, msg):
    print("  [%2d] OK  %s" % (n, msg))


def _load_pre_repair():
    src = subprocess.check_output(
        ["git", "show", "%s:solver/hilbert_holder.py" % PRE_REPAIR_PIN], cwd=HERE)
    mod = types.ModuleType("hilbert_holder_prerepair")
    mod.__file__ = "<git pre-repair>"
    exec(compile(src, mod.__file__, "exec"), mod.__dict__)
    return mod


def _rejects(fn):
    """(rejected, exception-or-None) -- never a bare boolean out of a silent path."""
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            fn()
    except Exception as exc:                                       # noqa: BLE001
        return True, exc
    return False, None


def main():
    with open(DATA) as fh:
        d = json.load(fh)
    print("Leg 169 -- hilbert_holder.py post-repair regression suite")
    print("  data: %s" % os.path.relpath(DATA, HERE))

    # -- 1 -- every one of leg 119's failing configurations is rejected at the LOW level
    bad = []
    for name, (a, g) in FAILING.items():
        rej, exc = _rejects(lambda a=a, g=g: HH.increment_pair_bound(1.0, 0.05, a, g))
        if not (rej and isinstance(exc, HH.HilbertHolderDomainError)):
            bad.append((name, type(exc).__name__ if exc else "returned a value"))
    assert not bad, (
        "increment_pair_bound no longer rejects leg 119's failing configuration(s) %r -- "
        "the bound-direction violation leg 119 measured (true/bound up to 1.2311 at "
        "delta = 1e-50) is REOPEN" % (bad,))
    _ok(1, "all %d of leg 119's failing configurations rejected at increment_pair_bound, "
           "every one with HilbertHolderDomainError" % len(FAILING))

    # -- 2 -- and at the ASSEMBLY level too; a guard on one entry point only is a half-fix
    bad = []
    for name, (a, g) in FAILING.items():
        rej, exc = _rejects(
            lambda a=a, g=g: HH.hilbert_holder_constant(a, g, n_theta=8, n_d=6, n_quad=60))
        if not (rej and isinstance(exc, HH.HilbertHolderDomainError)):
            bad.append((name, type(exc).__name__ if exc else "returned a value"))
    assert not bad, (
        "hilbert_holder_constant no longer rejects %r -- the public assembly API is the one "
        "a downstream consumer actually calls, and pre-repair it returned a FINITE "
        "(b_sup, b_semi) for gamma = -0.3 with only non-fatal warnings" % (bad,))
    _ok(2, "all %d rejected at the assembly hilbert_holder_constant as well -- both entry "
           "points guarded, not one" % len(FAILING))

    # -- 3 -- and NOTHING sound is rejected.  A guard that over-fires is also a regression.
    bad = []
    for name, (a, g) in SOUND.items():
        rej, exc = _rejects(lambda a=a, g=g: HH.increment_pair_bound(1.0, 0.05, a, g))
        if rej:
            bad.append((name, type(exc).__name__))
    assert not bad, (
        "the guard now rejects SOUND configuration(s) %r -- including possibly the shipped "
        "(1.5, 0.5) or the production (1.4, 0.15) optimum.  Clause (b) is broken" % (bad,))
    _ok(3, "0 of %d sound configurations wrongly rejected, shipped (1.5, 0.5) and "
           "production (1.4, 0.15) among them" % len(SOUND))

    # -- 4 -- the predicate is EXACTLY gamma > 0, not an epsilon-thresholded approximation
    assert not _rejects(lambda: HH.increment_pair_bound(1.0, 0.05, 1.5, 5e-324))[0], (
        "gamma = 5e-324 (the smallest positive float64) is now REJECTED -- the guard has "
        "acquired a threshold; the analytic predicate is gamma > 0 and nothing else")
    assert _rejects(lambda: HH.increment_pair_bound(1.0, 0.05, 1.5, 0.0))[0], (
        "gamma = 0.0 is now ACCEPTED -- the boundary itself is leg 119's violation V1")
    boundary = d["B5_leg_153_claims_rederived"]["iii_predicate_boundary_ladder"]
    assert boundary["n_disagreements"] == 0, (
        "the implemented predicate and gamma > 0 disagree on %d of the boundary ladder's "
        "probes" % boundary["n_disagreements"])
    _ok(4, "predicate is threshold-free: 5e-324 accepted, 0.0 rejected, 0 disagreements "
           "with gamma > 0 across the boundary ladder (-1e-12 .. 1e-6)")

    # -- 5 -- LESSON 90.  The control must be able to come out differently, LIVE.
    pre = _load_pre_repair()
    n_pre_accept, n_pre_silent_finite = 0, 0
    for name, (a, g) in FAILING.items():
        rej, _ = _rejects(lambda a=a, g=g: pre.increment_pair_bound(1.0, 0.05, a, g))
        if not rej:
            n_pre_accept += 1
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                v = pre.increment_pair_bound(1.0, 0.05, a, g)
            if all(math.isfinite(float(x)) for x in v):
                n_pre_silent_finite += 1
    assert n_pre_accept == len(FAILING), (
        "THE CONTROL IS DEAD.  The pre-repair blob %s accepts only %d of %d failing "
        "configurations; it should accept all of them.  Either the blob is not being loaded "
        "or it is the same object as the working tree, and every assertion above is a "
        "tautology about one module compared with itself"
        % (PRE_REPAIR_PIN, n_pre_accept, len(FAILING)))
    assert n_pre_silent_finite >= 5, (
        "the pre-repair arm returns a silent FINITE pair on only %d configurations "
        "(expected >= 5); the defect being regressed against has changed character"
        % n_pre_silent_finite)
    _ok(5, "LESSON-90 control LIVE: the pre-repair blob %s accepts %d/%d failing "
           "configurations and returns a silent finite pair on %d of them, where the "
           "repaired module raises on all %d"
        % (PRE_REPAIR_PIN, n_pre_accept, len(FAILING), n_pre_silent_finite, len(FAILING)))

    # -- 6 -- zero regression: the bitwise two-arm differential
    b3 = d["B3_clause_b_bitwise"]
    assert b3["n_leaves_moved"] == 0, (
        "%d of %d previously-validated float64 leaves MOVED between the pre-repair and "
        "repaired modules: %r.  Clause (b) fails and this is a repair regression"
        % (b3["n_leaves_moved"], b3["n_float64_leaves_compared"], b3["moved_examples"][:3]))
    assert not any(v.get("SHAPE_MISMATCH") for v in b3["per_surface"].values()), (
        "a surface changed SHAPE between the two arms -- a returned structure gained or "
        "lost a field, which no leaf-by-leaf comparison can see")
    assert b3["n_float64_leaves_compared"] >= 4400, (
        "the differential now compares only %d leaves (was 4505); the surface set has "
        "shrunk and '0 moved' is correspondingly weaker"
        % b3["n_float64_leaves_compared"])
    _ok(6, "clause (b): %d float64 leaves over %d surface groups compared with == (not "
           "allclose), %d moved"
        % (b3["n_float64_leaves_compared"], b3["n_surface_groups"], b3["n_leaves_moved"]))

    # -- 7 -- the capabilities-registered validated line, on BOTH arms
    b6 = d["B6_capabilities_validated_line"]
    assert b6["post_repair_exit_zero"], (
        "test_nk_hilbert_holder.py -- the line capabilities.py:368-371 registers as this "
        "module's validation -- no longer passes against the repaired module")
    assert b6["stdout_byte_identical"], (
        "the capabilities-registered test prints DIFFERENT output pre- and post-repair "
        "(%d differing lines: %r); a validated line has moved"
        % (b6["n_differing_lines"], b6["differing_lines"][:3]))
    _ok(7, "capabilities-registered test_nk_hilbert_holder.py: exit 0 post-repair and "
           "%d bytes of stdout byte-identical across the two arms"
        % b6["post_repair"]["n_stdout_bytes"])

    # -- 8 -- 'inflate' is honest: it never hands back a finite non-dominating pair
    b1 = d["B1_clause_a_per_case"]
    assert b1["n_inflate_returning_finite"] == 0, (
        "on_unsound='inflate' returned a FINITE pair on %d failing configurations.  At "
        "gamma <= 0 the exact majorant is unbounded, so the only honest answer is (inf, "
        "inf); a finite one is a new silent non-dominating bound"
        % b1["n_inflate_returning_finite"])
    for name in ("V1_gamma_0.0", "V2_gamma_-0.5"):
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            a, g = FAILING[name]
            v = HH.increment_pair_bound(1.0, 0.05, a, g, on_unsound="inflate")
        assert all(np.isinf(np.asarray(v, dtype=float))), (
            "on_unsound='inflate' at %s returned %r, not (inf, inf)" % (name, v))
    _ok(8, "on_unsound='inflate' returns the honest (inf, inf) on all %d failing "
           "configurations -- 0 finite non-dominating pairs" % len(FAILING))

    # -- 9 -- leg 147's shape: the rejections must be ALIKE, not merely numerous
    hom = b1["rejection_homogeneity"]
    assert hom["all_are_HilbertHolderDomainError"], (
        "the rejections are heterogeneous: types %r.  Leg 147's NO came from exactly this "
        "-- a clean headline count hiding one case that behaved differently from the rest"
        % (hom["distinct_exception_types"],))
    assert not hom["cases_whose_message_states_no_reason"], (
        "configuration(s) %r now raise with no stated reason; a rejection a caller cannot "
        "diagnose is the silent-failure mode in a different costume"
        % (hom["cases_whose_message_states_no_reason"],))
    _ok(9, "rejections homogeneous: 1 exception type across all %d cases and every message "
           "states its reason" % len(FAILING))

    # -- 10 -- leg 119's frozen runner: its abort is EXPECTED and is pinned as such
    b0 = d["B0_frozen_runner_abort_census"]
    assert b0["returncode"] != 0 and b0["aborted_in_gate"], (
        "leg 119's frozen runner p2_route_hha_v1_adversarial.py now RUNS TO COMPLETION "
        "against the repaired module.  That is not automatically wrong, but it means the "
        "guard no longer stops its bare gamma = 0.0 call at gate A3 -- re-check the guard "
        "before relaxing this pin")
    assert b0["n_gates_completed"] == 2 and b0["n_gates_total"] == 8, (
        "the frozen runner's abort point moved: %d of %d gates complete (was 2 of 8)"
        % (b0["n_gates_completed"], b0["n_gates_total"]))
    _ok(10, "leg 119's frozen runner still aborts as designed: exit %d at gate %s, %d of %d "
            "gates complete -- the battery is banked HERE, not there, precisely because of "
            "this" % (b0["returncode"], b0["aborted_in_gate"][0], b0["n_gates_completed"],
                      b0["n_gates_total"]))

    # -- 11 -- the HEAD_WARN_TOL band, on leg 153's grid AND on the grid the module ships
    h = d["B5_leg_153_claims_rederived"]["i_head_warning_band"]
    rep = h["reproduction_on_leg_153s_OWN_grid"]
    assert rep["shipped_matches_banked"] and rep["production_matches_banked"], (
        "on leg 153's OWN grid (24x14, n_quad=200) this leg no longer reproduces leg 153's "
        "banked head shares bitwise.  Until that reproduction holds, any disagreement on "
        "the shipped grid is a harness difference and not a resolution effect")
    for gname in ("leg_153_grid_24x14_nquad200", "SHIPPED_default_grid_48x28_nquad400"):
        assert h[gname]["band_still_separates"], (
            "HEAD_WARN_TOL = %g no longer sits strictly between the shipped and production "
            "worst head shares on %s; the warning band has stopped distinguishing the two "
            "configurations it was set to distinguish" % (h["HEAD_WARN_TOL"], gname))
    ge = h["grid_resolution_effect"]
    assert ge["shipped_ratio"] >= 1.0 and ge["production_ratio"] >= 1.0, (
        "refining the pair grid 24x14 -> 48x28 made a worst-case head share go DOWN "
        "(shipped %.4f x, production %.4f x).  A grid supremum can only under-report, so a "
        "ratio below 1 means the finer grid is not a refinement of the coarser one"
        % (ge["shipped_ratio"], ge["production_ratio"]))
    _ok(11, "HEAD_WARN_TOL band separates on BOTH grids; leg 153's 24x14 numbers reproduced "
            "bitwise (%.4eshipped / %.4e production) and the shipped 48x28 grid raises them "
            "%.4fx / %.4fx to %.4e / %.4e, margins %.2fx below / %.2fx above"
         % (ge["worst_shipped_24x14"], ge["worst_production_24x14"],
            ge["shipped_ratio"], ge["production_ratio"],
            ge["worst_shipped_48x28"], ge["worst_production_48x28"],
            ge["margin_below_shipped_48x28"], ge["margin_above_production_48x28"]))

    # -- the gate, and the leg's standing promise
    g = d["gate_answer"]
    assert g["clause_a_reject_or_dominate"] == "YES", "clause (a) answer changed"
    assert g["clause_b_bit_identical"] == "YES", "clause (b) answer changed"
    assert g["gate"] == "YES", "gate answer changed to %s" % g["gate"]
    assert not d["module_edited"], "this leg must never edit solver/hilbert_holder.py"

    print("\nALL HILBERT-HOLDER POST-REPAIR REGRESSION CHECKS PASSED")


if __name__ == "__main__":
    main()
