"""Spike-1 Step-C evidence: relaxing the rescaled solver to the Chen-Hou profile (the gate).

Data is generated by the logged gate run:
    .venv/bin/python experiments/spike1_stepC_gate.py --logged --steps 2500
        -> writeup/data/spike1_stepC_gate.json  (resolution study + predicate)
This script builds the figure from that committed JSON (no re-run):
    .venv/bin/python writeup/spike1_stepC_evidence.py
        -> writeup/figures/fig11_spike1_stepC_gate.png

Panels:
  A. c_omega and alpha=c_omega/c_l vs resolution, with the Chen-Hou targets -- convergence
     of the gauge-honest scalars (c_l is pinned by the gauge; c_omega/alpha are the real test).
  B. radial profile omega(r, beta~pi/4) log-log with an r^alpha reference -- the slow far-field tail.
  C. the pre-committed predicate checks + the finest-run numbers.
"""

import json
import sys
from pathlib import Path

import numpy as np

DATA = Path(__file__).resolve().parents[1] / "data"
FIGS = Path(__file__).resolve().parents[1] / "figures"
FIGS.mkdir(parents=True, exist_ok=True)
JSON = DATA / "spike1_stepC_gate.json"


def build_figure():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    d = json.loads(JSON.read_text())
    tgt = d["targets"]
    runs = d["runs"]
    study = sorted([r for r in runs if r["r_max"] == 1e5], key=lambda r: r["n_r"])
    fine = max(study, key=lambda r: r["n_r"])

    plt.rcParams.update({
        "figure.dpi": 130, "savefig.dpi": 130, "font.size": 10,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.grid": True, "grid.alpha": 0.25, "axes.axisbelow": True,
        "legend.frameon": False,
    })
    C_OM, C_AL, C_TGT, C_NUM = "#2563eb", "#7c3aed", "#dc2626", "#059669"
    fig, ax = plt.subplots(1, 3, figsize=(13.8, 4.2))

    # panel A: c_omega and alpha convergence vs n_r
    nr = np.array([r["n_r"] for r in study], float)
    com = np.array([r["c_omega"] for r in study])
    alp = np.array([r["alpha"] for r in study])
    ax0 = ax[0]
    l1 = ax0.plot(nr, com, "o-", color=C_OM, lw=1.7, label="$c_\\omega$")
    ax0.axhline(tgt["c_omega"], ls="--", color=C_OM, lw=1.0, alpha=0.6)
    ax0.set_xlabel("resolution $n_r$"); ax0.set_ylabel("$c_\\omega$", color=C_OM)
    ax0.tick_params(axis="y", labelcolor=C_OM)
    axb = ax0.twinx()
    axb.spines.top.set_visible(False)
    l2 = axb.plot(nr, alp, "s-", color=C_AL, lw=1.7, label="$\\alpha=c_\\omega/c_l$")
    axb.axhline(tgt["alpha"], ls="--", color=C_AL, lw=1.0, alpha=0.6)
    axb.set_ylabel("$\\alpha$", color=C_AL); axb.tick_params(axis="y", labelcolor=C_AL)
    axb.grid(False)
    ax0.set_title(f"A. Gauge-honest scalars converge\n(dashed = Chen-Hou: "
                  f"$c_\\omega${tgt['c_omega']:.3f}, $\\alpha${tgt['alpha']:.3f})")
    ax0.legend(l1 + l2, [ll.get_label() for ll in l1 + l2], loc="best", fontsize=8.5)

    # panel B: radial profile with r^alpha reference
    r = np.array(fine["cut_r"]); om = np.abs(np.array(fine["cut_omega"]))
    m = (r > 1e-2) & (om > 0)
    ax[1].loglog(r[m], om[m], color=C_NUM, lw=1.8, label="$|\\omega(r,\\beta{\\approx}\\pi/4)|$")
    rr = r[(r > fine["r_max"] ** 0.35) & (r < fine["r_max"] ** 0.72)]
    if len(rr) > 2:
        amp = om[np.argmin(np.abs(r - rr[0]))]
        ax[1].loglog(rr, amp * (rr / rr[0]) ** tgt["alpha"], "--", color=C_TGT, lw=1.3,
                     label=f"$r^{{{tgt['alpha']:.3f}}}$ (Chen-Hou)")
    ax[1].set_xlabel("r"); ax[1].set_ylabel("$|\\omega|$")
    ax[1].set_title(f"B. Slow far-field tail\n(fitted exponent {fine['alpha_far']:+.3f})")
    ax[1].legend(loc="best", fontsize=8.5)

    # panel C: predicate checks
    ax[2].axis("off")
    checks = d["predicate_checks"]
    verdict = d["predicate_pass"]
    lines = [f"PRE-COMMITTED PREDICATE:  {'PASS' if verdict else 'PARTIAL / FAIL'}", ""]
    labels = {"1_alpha_within_5pct": "1. $\\alpha$ within 5%",
              "2_alpha_far_within_10pct": "2. far-field exp within 10%",
              "3_anisotropy_below_0p23": "3. anisotropy $<0.23$ (2.24)",
              "4_resolution_stable_alpha": "4. $\\alpha$ resolution-stable"}
    for k in ["1_alpha_within_5pct", "2_alpha_far_within_10pct",
              "3_anisotropy_below_0p23", "4_resolution_stable_alpha"]:
        lines.append(f"  [{'PASS' if checks[k] else 'FAIL'}]  {labels[k]}")
    lines += ["", f"finest run  n_r={fine['n_r']}:",
              f"  $c_\\omega$={fine['c_omega']:+.4f}  (tgt {tgt['c_omega']:.4f})",
              f"  $\\alpha$={fine['alpha']:+.4f}  (tgt {tgt['alpha']:.4f})",
              f"  anisotropy={fine['anisotropy_median']:.3f}",
              f"  residual floor={fine['residual']:.2e}"]
    ax[2].text(0.02, 0.98, "\n".join(lines), va="top", ha="left", fontsize=9.5,
               family="monospace", transform=ax[2].transAxes)
    ax[2].set_title("C. Gate verdict")

    fig.suptitle("Spike 1 Step C — relaxing the rescaled 2D Boussinesq solver toward the "
                 "Chen-Hou self-similar profile", fontsize=11.5, y=1.02)
    fig.tight_layout()
    out = FIGS / "fig11_spike1_stepC_gate.png"
    fig.savefig(out, bbox_inches="tight")
    print(f"wrote {out}")


if __name__ == "__main__":
    if not JSON.exists():
        print("no committed JSON; run experiments/spike1_stepC_gate.py --logged first")
        sys.exit(1)
    build_figure()
