"""Fourier (circle) representation of the gCLM two-scale traveling-wave operator.

This is the Route-D *dress rehearsal* layer: the same residual the GA scored on a
grid (solver/gclm_family.py::GCLMResidual.residual_two_scale), but written EXACTLY
in the compactified Fourier basis discovered in the Route-D v1 probe (§Q3/Q4 of
writeup/4_p2_lottery/TECHNICAL_P2_ROUTED.md).  No grid, no quadrature: every
coefficient below is a closed-form polynomial in the unknowns, so a
Newton-Kantorovich (NK) radii-polynomial computation can be assembled on top of it
(first in plain float -- the dress rehearsal -- and only afterwards in interval
arithmetic, solver/interval.py).

THE CHANGE OF VARIABLE.  X = tan(theta/2), theta in (-pi, pi); X = +-infinity is
theta = +-pi.  Then

    e^{i theta} = (1 + iX)/(1 - iX)

is holomorphic in the upper half X-plane (its only pole is at X = -i) and tends to
-1 at infinity, so G_k(X) := e^{i k theta} - (-1)^k lies in the Hardy space and
decays.  With the convention H(f)(x) = (1/pi) p.v. int f(y)/(x-y) dy one has
H(Re G) = Im G for such G, hence -- unconditionally, for every k >= 0 --

    H(cos k theta) = sin k theta,          H(1) = 0.                        (H)

That is the exact statement behind the ~1e-7 numerical check of Route-D v1 Q3
(which was run on endpoint-vanishing combinations only; the identity in fact needs
no decay assumption -- the constant is simply annihilated).

THE DERIVATIVE.  dX/dtheta = (1/2) sec^2(theta/2) = 1/(1 + cos theta), so

    f_X = (1 + cos theta) f_theta.                                          (D)

The factor (1 + cos theta) VANISHES to second order at theta = +-pi.  This is not
cosmetic: it is the far-field degeneracy that the dress rehearsal measures.

THE OBJECT.  Omega even and real, Omega = sum_{k>=0} a_k cos(k theta); the a=0
two-scale residual is

    F(Omega, c) = Omega H(Omega) - c Omega_X,                              (TW)

which is ODD (Omega even => Omega H(Omega) odd by (H), Omega_X odd by (D)), so
F = sum_{m>=1} b_m sin(m theta).  The exact anchor is Omega_2 = -1/(1+X^2) =
-(1 + cos theta)/2, i.e. a = (-1/2, -1/2, 0, 0, ...), with c = 1/2; `residual`
below returns b == 0 for it to machine precision (test_nk_fourier.py gate 1).

All routines here are plain float.  They are deliberately written as small dense
loops over modes (N is tens, not thousands) so that the SAME code path can later be
re-run with `solver.interval.Interval` scalars.
"""

import numpy as np

# ---------------------------------------------------------------------------
# sine-coefficient bookkeeping
# ---------------------------------------------------------------------------


def _add_sin(out, m, val):
    """Accumulate `val * sin(m theta)` into the coefficient array `out` (1-indexed).

    Folds the two conventions that bite in this basis: sin(0) == 0 (dropped) and
    sin(-m) == -sin(m) (folded onto |m| with a sign flip).  Modes beyond len(out)
    are discarded by the caller's choice of array length -- callers that need the
    full (untruncated) residual must size `out` to hold every generated mode.
    """
    if m == 0:
        return
    if m < 0:
        m, val = -m, -val
    if m <= len(out):
        out[m - 1] += val


def n_modes_residual(K):
    """Highest sine mode generated by F for a degree-K cosine profile (= 2K)."""
    return max(2 * K, 1)


# ---------------------------------------------------------------------------
# the residual and its derivatives, in closed form
# ---------------------------------------------------------------------------


def residual(a, c, M=None):
    """Sine coefficients b_1..b_M of F(Omega, c) = Omega H(Omega) - c Omega_X.

    `a` is the cosine-coefficient vector (a[0] = a_0, degree K = len(a)-1).  With
    M=None the full, untruncated residual (M = 2K modes) is returned, so nothing
    is silently dropped; pass M to truncate deliberately.

    Term by term, using (H) and (D):
      Omega H(Omega) = sum_{k>=0} sum_{j>=1} a_k a_j cos(k th) sin(j th)
                     = (1/2) sum a_k a_j [ sin((j+k) th) + sin((j-k) th) ]
      -c Omega_X     = -c (1 + cos th) Omega_theta,  Omega_theta = -sum k a_k sin(k th)
                     = c sum_k k a_k [ sin(k th) + (1/2) sin((k+1) th)
                                                 + (1/2) sin((k-1) th) ]
    """
    a = np.asarray(a, dtype=float)
    K = a.size - 1
    M = n_modes_residual(K) if M is None else int(M)
    b = np.zeros(M)

    # quadratic stretching term Omega * H(Omega)
    for k in range(0, K + 1):
        ak = a[k]
        if ak == 0.0:
            continue
        for j in range(1, K + 1):           # H kills the j=0 (constant) mode
            aj = a[j]
            if aj == 0.0:
                continue
            w = 0.5 * ak * aj
            _add_sin(b, j + k, w)
            _add_sin(b, j - k, w)

    # transport term -c Omega_X
    for k in range(1, K + 1):
        w = c * k * a[k]
        if w == 0.0:
            continue
        _add_sin(b, k, w)
        _add_sin(b, k + 1, 0.5 * w)
        _add_sin(b, k - 1, 0.5 * w)

    return b


def jacobian(a, c, M=None, n_cols=None):
    """d(b_m)/d(a_k): the linearization DF of `residual` w.r.t. the profile.

    Rows m = 1..M (sine modes), columns k = 0..n_cols-1 (cosine modes).  With
    n_cols > len(a) the extra columns are the action of DF on modes the current
    profile does not excite -- exactly what the NK tail analysis needs (the
    columns are still exact, because DF is linear in the perturbation).

    DF[h] = h H(Omega) + Omega H(h) - c h_X, so column k receives
      (i)  cos(k th) H(Omega)              [ all k >= 0 ]
      (ii) Omega sin(k th)                 [ k >= 1 only, by (H) ]
      (iii) c k [ sin(k th) + (1/2) sin((k+1) th) + (1/2) sin((k-1) th) ]
    """
    a = np.asarray(a, dtype=float)
    K = a.size - 1
    n_cols = (K + 1) if n_cols is None else int(n_cols)
    M = n_modes_residual(max(K, n_cols - 1)) if M is None else int(M)
    J = np.zeros((M, n_cols))

    for k in range(0, n_cols):
        col = J[:, k]
        # (i) cos(k th) * H(Omega) = sum_{j>=1} a_j cos(k) sin(j)
        for j in range(1, K + 1):
            if a[j] == 0.0:
                continue
            w = 0.5 * a[j]
            _add_sin(col, j + k, w)
            _add_sin(col, j - k, w)
        if k >= 1:
            # (ii) Omega * sin(k th) = sum_{i>=0} a_i cos(i) sin(k)
            for i in range(0, K + 1):
                if a[i] == 0.0:
                    continue
                w = 0.5 * a[i]
                _add_sin(col, k + i, w)
                _add_sin(col, k - i, w)
            # (iii) transport
            w = c * k
            _add_sin(col, k, w)
            _add_sin(col, k + 1, 0.5 * w)
            _add_sin(col, k - 1, 0.5 * w)
    return J


def dc_column(a, M=None):
    """dF/dc = -Omega_X, as sine coefficients (the rank-1 speed column)."""
    a = np.asarray(a, dtype=float)
    K = a.size - 1
    M = n_modes_residual(K) if M is None else int(M)
    col = np.zeros(M)
    for k in range(1, K + 1):
        w = k * a[k]                      # -Omega_X = +sum k a_k (1+cos) sin(k)/1
        if w == 0.0:
            continue
        _add_sin(col, k, w)
        _add_sin(col, k + 1, 0.5 * w)
        _add_sin(col, k - 1, 0.5 * w)
    return col


# ---------------------------------------------------------------------------
# the anchor and its symmetry directions
# ---------------------------------------------------------------------------

C_ANCHOR = 0.5


def anchor(N):
    """The exact a=0 two-scale anchor as a degree-N cosine vector.

    Omega_2 = -1/(1+X^2) = -(1 + cos theta)/2  ->  a_0 = a_1 = -1/2, rest 0.
    """
    a = np.zeros(N + 1)
    a[0] = -0.5
    if N >= 1:
        a[1] = -0.5
    return a


def kernel_directions(N):
    """The two exact tangent directions of the a=0 scaling valley at the anchor.

    Every Lorentzian Omega = A/(1 + B X^2) is an exact traveling wave with speed
    c = -A/(2 sqrt(B)), so the zero set is the 2-parameter surface (A, B).
    Differentiating at (A, B) = (-1, 1):

      d/dA : Omega -> 1/(1+X^2) = (1 + cos)/2,  c -> -1/2
             => (a; dc) = ((1/2, 1/2, 0, ...); -1/2)          [amplitude scaling]
      d/dB : Omega -> X^2/(1+X^2)^2 = sin^2(theta)/4 = (1 - cos 2theta)/8,
             c -> -1/4
             => (a; dc) = ((1/8, 0, -1/8, 0, ...); -1/4)      [dilation]

    Returns [(v1, dc1), (v2, dc2)] with v of length N+1.  Both are annihilated by
    the un-gauged [DF | dF/dc] (test_nk_fourier.py gate 3) -- this is the analytic
    version of the Route-D v1 Q2 singular-value count.
    """
    v1 = np.zeros(N + 1)
    v1[0] = 0.5
    if N >= 1:
        v1[1] = 0.5
    v2 = np.zeros(N + 1)
    v2[0] = 0.125
    if N >= 2:
        v2[2] = -0.125
    return [(v1, -0.5), (v2, -0.25)]


# ---------------------------------------------------------------------------
# gauge functionals (the Q2 "two scalar conditions")
# ---------------------------------------------------------------------------

GAUGES = {
    # Omega(X=0) = Omega(theta=0) = sum_k a_k  -- the origin normalization
    "origin": (lambda N: np.ones(N + 1), -1.0),
    # a_0 alone (the mean of Omega over theta)
    "a0": (lambda N: np.eye(N + 1)[0], -0.5),
    # a_1 alone (the leading oscillatory amplitude)
    "a1": (lambda N: np.eye(N + 1)[1], -0.5),
}


def gauge_row(name, N):
    """(gradient, target) of the scalar normalization functional `name`."""
    grad_fn, target = GAUGES[name]
    return grad_fn(N), target


def gauged_system(a, c, N, gauge="origin"):
    """The square (N+1)x(N+1) system: [normalization ; sine modes 1..N].

    Speed c is FIXED (gauge condition 1) and one scalar normalization is imposed
    (gauge condition 2) -- exactly the two conditions Route-D v1 Q2 counted.
    Returns (G, J) with G the residual vector and J = dG/da.
    """
    grad, target = gauge_row(gauge, N)
    G = np.empty(N + 1)
    J = np.empty((N + 1, N + 1))
    G[0] = float(np.dot(grad, a)) - target
    J[0, :] = grad
    G[1:] = residual(a, c, M=N)
    J[1:, :] = jacobian(a, c, M=N, n_cols=N + 1)
    return G, J


# ---------------------------------------------------------------------------
# norms
# ---------------------------------------------------------------------------


def ell1_op_norm(M):
    """Induced ell^1 -> ell^1 operator norm = max absolute COLUMN sum."""
    M = np.atleast_2d(np.asarray(M, dtype=float))
    return float(np.abs(M).sum(axis=0).max()) if M.size else 0.0


def weighted_ell1_op_norm(M, w_dom, w_cod):
    """Induced norm of M for ||x|| = sum w_dom_k |x_k|, ||y|| = sum w_cod_m |y_m|.

    ||M|| = max_k (1 / w_dom_k) * sum_m w_cod_m |M_mk|  (weighted column sums).
    """
    M = np.atleast_2d(np.asarray(M, dtype=float))
    if M.size == 0:
        return 0.0
    cols = (np.abs(M) * np.asarray(w_cod, dtype=float)[:, None]).sum(axis=0)
    return float((cols / np.asarray(w_dom, dtype=float)).max())


# ---------------------------------------------------------------------------
# radii polynomial
# ---------------------------------------------------------------------------


def radii_polynomial(Y0, Z0, Z1, Z2):
    """Standard radii-polynomial test p(r) = Z2 r^2 - (1 - Z0 - Z1) r + Y0.

    Returns a dict with the contraction budget `one_minus_Z`, the discriminant,
    whether the ball CLOSES (a positive root interval exists), the smaller root
    r_min (the certified radius), and -- the number this dress rehearsal is really
    after -- `Y0_max`, the LARGEST defect that would still close at these Z's:

        Y0_max = (1 - Z0 - Z1)^2 / (4 Z2).

    Y0_max is the "certification budget": compare it against the residual floor of
    an approximate profile to see whether certifying that profile is even
    arithmetically conceivable.
    """
    one_minus_Z = 1.0 - Z0 - Z1
    disc = one_minus_Z ** 2 - 4.0 * Z2 * Y0
    closes = bool(one_minus_Z > 0.0 and disc >= 0.0 and Z2 > 0.0)
    r_min = float((one_minus_Z - np.sqrt(disc)) / (2.0 * Z2)) if closes else float("nan")
    r_max = float((one_minus_Z + np.sqrt(disc)) / (2.0 * Z2)) if closes else float("nan")
    Y0_max = float(one_minus_Z ** 2 / (4.0 * Z2)) if (one_minus_Z > 0 and Z2 > 0) else 0.0
    return {
        "Y0": float(Y0), "Z0": float(Z0), "Z1": float(Z1), "Z2": float(Z2),
        "one_minus_Z": float(one_minus_Z), "discriminant": float(disc),
        "closes": closes, "r_min": r_min, "r_max": r_max, "Y0_max": Y0_max,
    }


# ---------------------------------------------------------------------------
# the far-field (tail) block
# ---------------------------------------------------------------------------


def tail_band(k, c=C_ANCHOR):
    """The three exact DF entries of far-field column k, at the anchor.

    With Omega_2 = -1/2 - (1/2) cos and H(Omega_2) = -(1/2) sin, column k of
    DF collects, mode by mode,

      term (i)   cos(k) H(Omega_2) :  m=k+1 -> -1/4,  m=k-1 -> +1/4
      term (ii)  Omega_2 sin(k)    :  m=k   -> -1/2,  m=k+-1 -> -1/4
      term (iii) transport c k     :  m=k   -> +c k,  m=k+-1 -> +c k / 2

    so the column is (sub, diag, sup) = (c k / 2,  c k - 1/2,  c k / 2 - 1/2)
    on rows (k-1, k, k+1) and ZERO elsewhere -- the tridiagonality of Route-D v1
    Q4, now in closed form rather than as a grid cross-check.
    """
    k = int(k)
    return (0.5 * c * k, c * k - 0.5, 0.5 * c * k - 0.5)


def tail_Z1_column(k, c=C_ANCHOR, diag="transport"):
    """ell^1 column weight of A_tail (A_dagger - DF) at far-field mode k.

    The finite-section NK recipe approximates the far field of DF by its diagonal
    Lambda and sets A_tail = diag(1/Lambda_m); everything discarded then lands in
    Z1 = ||A (A_dagger - DF)||.  With the exact band of `tail_band`, column k
    contributes

        z(k) = |sub| / |Lambda_{k-1}| + |sup| / |Lambda_{k+1}|.

    Two natural choices of Lambda bracket the answer:
      diag="transport"  Lambda_m = c m           (the pure transport diagonal)
          z(k) = (c k / 2)/(c (k-1)) + (c k / 2 - 1/2)/(c (k+1))  ->  1 FROM BELOW
      diag="exact"      Lambda_m = c m - 1/2     (the true DF diagonal)
          z(k) = (c k / 2)/(c(k-1) - 1/2) + (c k / 2 - 1/2)/(c(k+1) - 1/2)
                                                 ->  1 FROM ABOVE

    BOTH tend to 1, from opposite sides, at rate O(1/k), and the limit is
    independent of c.  That is the whole story: the far field is EXACTLY MARGINAL.
    The reason is structural -- the transport term is c (1 + cos theta) d_theta and
    the symbol 1 + cos(phi) has ell^1 norm 2, exactly twice its own mean, because
    it VANISHES at phi = pi (i.e. at X = infinity).  Whatever the truncation N,
    sup_{k>N} z(k) = 1, so 1 - Z0 - Z1 <= 0 and the radii polynomial cannot close.
    Sharpening the tail model does not help (`tail_weight_obstruction`): it only
    moves the divergence from Z1 into ||A||.
    """
    k = int(k)
    if k < 2:
        raise ValueError("tail column analysis applies to k >= 2")
    sub, _, sup = tail_band(k, c)
    if diag == "transport":
        lo, hi = c * (k - 1), c * (k + 1)
    elif diag == "exact":
        # the TRUE diagonal c m - 1/2 vanishes at m = 1/(2c) (m = 1 for c = 1/2),
        # so this model only describes the far field, k >= 1/(2c) + 2
        if c * (k - 1) - 0.5 <= 0.0:
            raise ValueError(f"exact-diagonal tail model needs k > {0.5 / c + 1:g}")
        lo, hi = c * (k - 1) - 0.5, c * (k + 1) - 0.5
    else:
        raise ValueError(f"unknown diag model {diag!r}")
    return float(abs(sub) / abs(lo) + abs(sup) / abs(hi))


def tail_weight_obstruction(w, k_lo, k_hi, c=C_ANCHOR):
    """Weighted-ell^1 version of `tail_Z1_column`, for a domain weight w(k).

    With weight w the column weight becomes

        z_w(k) = [ w(k-1) k / (2 (k-1)) + w(k+1) k / (2 (k+1)) ] / w(k)
               = ( u(k-1) + u(k+1) ) / (2 u(k)),      u(k) := w(k) / k.

    (up to the O(1/k) corrections of `tail_band`, which do not change the limit).
    z_w(k) <= 1 - delta for all large k forces u(k+1) <= 2(1-delta) u(k) - u(k-1);
    that recursion's characteristic roots (1-delta) +- i sqrt(1 - (1-delta)^2) sit
    ON the unit circle with argument arccos(1-delta) > 0, so every solution
    oscillates and any positive sequence obeying it must change sign in finitely
    many steps.  Hence NO positive weight achieves a uniform Z1 < 1: the best
    possible is u affine (w(k) = k(alpha + beta k)), which gives z_w == 1 exactly.
    Returns the sup of z_w over [k_lo, k_hi] so an experiment can display it.
    """
    ks = np.arange(int(k_lo), int(k_hi) + 1)
    u = np.array([w(int(k)) / k for k in range(int(k_lo) - 1, int(k_hi) + 2)])
    z = (u[:-2] + u[2:]) / (2.0 * u[1:-1])
    return float(np.max(z)), ks, z
